name: check syntax

on:
  push:
    branches: [ FAST ]
  pull_request:
    branches: [ FAST ]

jobs:
  VerifyFiles:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: check json syntax
      run: |
        cd ${{github.workspace}}/script
        python check_file.py
